# Generated by Django 6.0 on 2025-12-12 10:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_is_active_user_is_staff_alter_user_is_superuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userAllergies',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userBloodGroup',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userDiseases',
        ),
        migrations.RemoveField(
            model_name='user',
            name='userGenotype',
        ),
        migrations.CreateModel(
            name='LaboProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='labo_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='MedecinProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hospital', models.CharField(max_length=50, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medecin_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userAllergies', models.TextField(blank=True, null=True)),
                ('userDiseases', models.TextField(blank=True, null=True)),
                ('userGenotype', models.CharField(blank=True, choices=[('AA', 'Aa'), ('AS', 'As'), ('SS', 'Ss'), ('AC', 'Ac'), ('SC', 'Sc')], max_length=5, null=True)),
                ('userBloodGroup', models.CharField(choices=[('A+', 'A Pos'), ('A-', 'A Neg'), ('B+', 'B Pos'), ('B-', 'B Neg'), ('AB+', 'Ab Pos'), ('AB-', 'Ab Neg'), ('O+', 'O Pos'), ('O-', 'O Neg')], max_length=5)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
