"""
Django settings for config project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
import dj_database_url  # Pour parser l'URL de la BD de Render
import environ  # Pour gérer les variables d'environnement
from corsheaders.defaults import default_methods, default_headers
from pathlib import Path
from datetime import timedelta

# Initialisation de django-environ
env = environ.Env(
    # Définir le type et la valeur par défaut si la variable n'est pas trouvée
    DEBUG=(bool, True),
    # Clé locale par défaut à NE PAS UTILISER en production
    SECRET_KEY=(str, "django-insecure-%724rlap6vt#a&6b)_+-1j(vxa6s46@-afn(-x@dy@sy)ybf!2")
)

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production

# -----------------
# 1. Variables de Sécurité et Environnement
# -----------------
# Lire les variables d'environnement ou utiliser les valeurs par défaut
SECRET_KEY = env('SECRET_KEY')
DEBUG = env('DEBUG')

# Si DEBUG est False (production), ALLOWED_HOSTS doit être défini via l'environnement
if not DEBUG:
    # L'hôte de Render sera inclus ici
    ALLOWED_HOSTS = env.list('ALLOWED_HOSTS', default=['.render.com'])
    # Sécurité en production
    CSRF_TRUSTED_ORIGINS = ['https://*.render.com']
    # Sécurité: forcer HTTPS
    SECURE_SSL_REDIRECT = True
    SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
else:
    # En développement
    ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "corsheaders",
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "drf_spectacular_sidecar",
    "users",

]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    # Whitenoise DOIT être après SecurityMiddleware
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "config.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "config.wsgi.application"


# -----------------
# 2. Base de Données (PostgreSQL)
# -----------------
if not DEBUG:
    # En production, utilisez la variable d'environnement DATABASE_URL fournie par Render
    DATABASES = {
        'default': dj_database_url.config(
            conn_max_age=600,
            ssl_require=True  # Important pour Render
        )
    }
else:
    # En développement, utilisez votre configuration locale
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.postgresql",
            "NAME": "tohpitoh_db",
            "USER": "tohpitoh_user",
            "PASSWORD": "abcdef123456",
            "HOST": "localhost",
            "PORT": "5432",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators
AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/
LANGUAGE_CODE = "en-us"
TIME_ZONE = "UTC"
USE_I18N = True
USE_TZ = True


# -----------------
# 3. Fichiers Statiques (Static Files)
# -----------------
# Le chemin où les fichiers statiques collectés seront placés par `collectstatic`
STATIC_ROOT = BASE_DIR / "staticfiles"
STATIC_URL = "/static/"

# Activer la compression et le cache des statiques par Whitenoise
if not DEBUG:
    STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# REST Framework, JWT, CORS, SPECTACULAR (inchangé, sauf CORS pour l'environnement)

REST_FRAMEWORK = {
    "DEFAULT_PAGINATION_CLASS": "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10,
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
    ),
    "DEFAULT_PERMISSION_CLASSES": ("rest_framework.permissions.IsAuthenticated",),
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
}

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(minutes=360),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=1),
}

AUTH_USER_MODEL = "users.User"

# CORS configuration
CORS_ALLOW_ALL_ORIGINS = True # Peut être défini sur False en production par mesure de sécurité
# CORS_ALLOWED_ORIGINS devrait inclure votre domaine Render en production si CORS_ALLOW_ALL_ORIGINS = False
CORS_ALLOWED_ORIGINS = [
    "exp://10.39.131.206:8081", # Pour votre application Expo locale
    # Ajoutez ici votre domaine Render (ex: "https://votre-projet.onrender.com")
]

CORS_ALLOW_METHODS = [
    *default_methods,
]

CORS_ALLOW_HEADERS = [
    *default_headers,
]

SPECTACULAR_SETTINGS = {
    "TITLE": "Tohpitoh Backend",
    "DESCRIPTION": "Documentation auto-générée.",
    "VERSION": "1.0.0",
}
